### ISSUE TITLE
Run simultaneously on multiple environments?

### ISSUE THREAD

**Issue by jeanconn** [sot/testr#13]
I was wondering about running ska_testr against multiple environments at the same time.  In that setup, it looks like the `last` symlink from testr would be ambiguous.  What is `last` supposed to really be used for?

**Comment by taldcroft** [comment]
The `last` link is a bit of a leftover from when the default was to make a new directory for every run of testr.  You can just ignore it though.

**Comment by jeanconn** [comment]
Good to know.  Thanks.
